FROM node:16-alpine

ENV PORT 1338
# Set up the working directory that will be used to copy files/directories below :
RUN mkdir -p /usr/src/app/backend/
WORKDIR /usr/src/app/backend

# Installing dependencies
COPY package*.json ./package-lock.json /usr/src/app/backend/
WORKDIR /usr/src/app/backend
RUN npm install

COPY . .
RUN npm run build

EXPOSE 1338

CMD ["npm","run","dev"]